### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.2 compiler

### ISSUE THREAD

**Issue by AlokMishra01** [ayyshim/esewa_pnp#12]
When I open the project in Xcode and try to build the project I get the Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.2 compiler error.  First I was using code 12.3 now I am using 12.1 but still, I get the same error.

**Comment by ayyshim** [comment]
I am aware of this error and soon I will work on it. But for now I can't because I have to prepare for exams. Will let you know as soon as this error is fixed.

**Comment by AlokMishra01** [comment]
Thanks. I like what you are doing if you need any help let me know.

**Comment by ayyshim** [comment]
I have recently published new version, [1.0.3](https://pub.dev/packages/esewa_pnp), of this plugin. Please use it.

Read the new [README.md ](https://github.com/ayyshim/esewa_pnp/blob/master/README.md) file before using new version of this plugin. There are some minor changes from previous version.

**Comment by AlokMishra01** [comment]
Still showing the same error Swift 5.2.4 cannot be imported by the Swift 5.3

**Comment by ayyshim** [comment]
What version of xcode are you using? This plugin is compatible with latest 12.3 and swift version 5.3.2.

**Comment by ayyshim** [comment]
That's very unlikely because plugin is compiled with 5.3.2. Make sure you are using esewa_pnp 1.0.3 and please run `flutter clean` and `flutter pub get`.

**Comment by AlokMishra01** [comment]
Again I tried everything but I get an error Swift 5.3.1 cannot be imported by the Swift 5.3. I am using Xcode 12.1.

**Comment by ayyshim** [comment]
The latest version of xcode is 12.3 and swift is 5.3.2. Please update you xcode to latest version. ESewa ios framework does not support backward compatibility so you and I have to update xcode to use ESewa framework.

**Comment by AlokMishra01** [comment]
Swift error is solved but now I get error `Could not find module 'EsewaSDK for target 'x86_64-apple-ios-simulator; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7`

**Comment by ayyshim** [comment]
It seems like you are trying to test esewa_pnp plugin in simulator. Try adding esewa_pnp in your pubspec.yaml file like this

```yaml
dependencies:
  # esewa_pnp: ^1.0.4 # Use it on production app or while testing esewa_pnp on real physical iOS device.
  esewa_pnp:
      git:
          url: git://github.com/ayyshim/esewa_pnp.git
          ref: dev
```

**Comment by AlokMishra01** [comment]
Same error when I build for release.

**Comment by ayyshim** [comment]
Can you message me on facebook? I could assist you there.
Link: https://m.me/ayyshim

**Comment by AlokMishra01** [comment]
Issue Solve after 1.0.3 version.

**Comment by aarjan** [comment]
Hey @ayyshim, 
I get this error while using the latest version, 1.0.6.
```
 /flutter/.pub-cache/hosted/pub.dartlang.org/esewa_pnp-1.0.6/ios/Classes/SwiftEsewaPnpPlugin.swift:3:8: error: module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4 compiler:
    /flutter_app/ios/.symlinks/plugins/esewa_pnp/ios/EsewaSDK.framework/Modules/EsewaSDK.swiftmodule/arm64-apple-ios.swiftmodule
   import EsewaSDK
           ^
    /flutter_app/ios/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Wpointer-to-int-cast]    
      NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
    
    ```
